### PR TITLE
Change "Treatment"  to "Group" in mapping

### LINKED ISSUE #17: change 'Treatment variable' label to 'Grouping Variable' in mapping
This is to encourage user to group the data by factors other than treatment, e.g. age, or to encourage use for open label studies with no treatment groups

### PR DESCRIPTION
**Pull request by xni7**
# Overview

See issue #17 .  In many ongoing trials, treatment are still blinded. Therefore grouping by treatment is not always meaningful. This PR changed "Treatment" to "Group" in the dm meta data and the mapping. 

# Test notes

- Code review the changes
- Pull the new branch and run [inst/deploy/app.R](https://github.com/SafetyGraphics/qtexplorer/compare/17-change-treatment-variable-label?expand=1#diff-390a8b033a1ed8c35c44f6280c800beb8a78aa8f597184792eeb0b40180d4f85)

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
A couple of things to check before merging the code:

1. meta_dm: Perhaps change the label to 'Group Column' as it looks a bit more professional if the capitalisation is consistent
2. app.R: Is the purpose of this file to run a test of the app? If so, can we remove the commented out code on this?
3. app.R: I got the following errors when running this code. If the user is intended to run this code to test out the app, then I think this should be able to run error-free with no modification from the user. Can you please check if you also get these errors?

> meta1 <- makeMeta(qtCharts)
Error in makeMeta(qtCharts) : could not find function "makeMeta"

> safetyGraphicsApp(
    charts = qtCharts,
    domainData = list(ecg = eg_ph2_new, dm = qtexplorer::dm_ph2),
    mapping = mapping_ph2
  , runNow = FALSE
 )
Error in safetyGraphicsApp(charts = qtCharts, domainData = list(ecg = eg_ph2_new,  : 
  unused argument (runNow = FALSE)

**Comment by xni7** [comment]
Good points @Rosie-L . 1&2 fixed 

For 3, users need the new `makeMeta()` function in [release 2.1.0](https://github.com/SafetyGraphics/safetyGraphics/releases/tag/v2.1.0)

**Review by ghost — CHANGES_REQUESTED** [review]
I think the last SafetyGraphicsApp call need to be modified in order to run, e.g.  as follows:

 safetyGraphicsApp(
    charts = qtCharts,
    domainData = list(ecg = eg_ph2_new, dm = qtexplorer::dm_ph2),
    meta = meta1,
    mapping = mapping_ph2
 )

**Comment by xni7** [comment]
> I think the last SafetyGraphicsApp call need to be modified in order to run, e.g. as follows:
> 
> safetyGraphicsApp( charts = qtCharts, domainData = list(ecg = eg_ph2_new, dm = qtexplorer::dm_ph2), meta = meta1, mapping = mapping_ph2 )

Calling out meta parameter is optional as in [Cookbook Example 11](https://github.com/SafetyGraphics/safetyGraphics/wiki/Cookbook#example-11---create-a-hello-world-data-domain-and-chart). It wouldn't hurt to be more explicit though. I can add meta1 in the example here.

**Pull request merged**
